import { Octokit } from '@octokit/rest';
import type { ChangeAnalysis } from '../analyzer/change-summarizer.js';

export interface CommentOptions {
  owner: string;
  repo: string;
  pullNumber: number;
  analysis: ChangeAnalysis;
  recordingUrl?: string;
  screenshots?: string[];
  script: string;
  rerunUrl?: string;
}

const COMMENT_MARKER = '<!-- git-glimpse-demo -->';

export interface SkipCommentOptions {
  owner: string;
  repo: string;
  pullNumber: number;
  reason: string;
}

export async function postSkipComment(
  token: string,
  options: SkipCommentOptions
): Promise<{ commentId: number; url: string }> {
  const octokit = new Octokit({ auth: token });

  const body = `${COMMENT_MARKER}
## GitGlimpse — Skipped

${options.reason}

---
*Generated by [git-glimpse](https://github.com/DeDuckProject/git-glimpse)*`;

  const existing = await findExistingComment(octokit, options);

  if (existing) {
    const response = await octokit.rest.issues.updateComment({
      owner: options.owner,
      repo: options.repo,
      comment_id: existing.id,
      body,
    });
    return { commentId: response.data.id, url: response.data.html_url };
  }

  const response = await octokit.rest.issues.createComment({
    owner: options.owner,
    repo: options.repo,
    issue_number: options.pullNumber,
    body,
  });

  return { commentId: response.data.id, url: response.data.html_url };
}

export async function postPRComment(
  token: string,
  options: CommentOptions
): Promise<{ commentId: number; url: string }> {
  const octokit = new Octokit({ auth: token });

  const body = buildCommentBody(options);

  // Check for an existing git-glimpse comment to update instead of creating a new one
  const existing = await findExistingComment(octokit, options);

  if (existing) {
    const response = await octokit.rest.issues.updateComment({
      owner: options.owner,
      repo: options.repo,
      comment_id: existing.id,
      body,
    });
    return { commentId: response.data.id, url: response.data.html_url };
  }

  const response = await octokit.rest.issues.createComment({
    owner: options.owner,
    repo: options.repo,
    issue_number: options.pullNumber,
    body,
  });

  return { commentId: response.data.id, url: response.data.html_url };
}

async function findExistingComment(
  octokit: Octokit,
  options: Pick<CommentOptions, 'owner' | 'repo' | 'pullNumber'>
): Promise<{ id: number } | null> {
  const comments = await octokit.rest.issues.listComments({
    owner: options.owner,
    repo: options.repo,
    issue_number: options.pullNumber,
    per_page: 100,
  });

  const existing = comments.data.find((c) => c.body?.includes(COMMENT_MARKER));
  return existing ? { id: existing.id } : null;
}

function buildCommentBody(options: CommentOptions): string {
  const { analysis, recordingUrl, screenshots, script, rerunUrl } = options;

  const changedFilesList = analysis.changedFiles
    .slice(0, 5)
    .map((f) => `\`${f}\``)
    .join(', ');
  const moreFiles = analysis.changedFiles.length > 5
    ? ` (+${analysis.changedFiles.length - 5} more)`
    : '';

  const mediaSection = recordingUrl
    ? `![Demo](${recordingUrl})\n\n[📱 Can't see the preview? Open it directly](${recordingUrl})`
    : screenshots && screenshots.length > 0
    ? screenshots
        .map((s, i) => `![Screenshot ${i + 1}](${s})\n\n[📱 Can't see screenshot ${i + 1}? Open it directly](${s})`)
        .join('\n\n')
    : '_No recording available._';

  const rerunSection = rerunUrl ? `\n\n[↺ Re-run demo](${rerunUrl})` : '';

  return `${COMMENT_MARKER}
## 🧐 UI Demo Preview

**Changes detected in**: ${changedFilesList}${moreFiles}

**What changed**: ${analysis.changeDescription}

${mediaSection}

<details>
<summary>Demo script (auto-generated)</summary>

\`\`\`typescript
${script}
\`\`\`
</details>

---
*Generated by [git-glimpse](https://github.com/DeDuckProject/git-glimpse) ![git-glimpse logo](https://raw.githubusercontent.com/DeDuckProject/git-glimpse/main/assets/logo_square_small.png)${rerunSection}*`;
}
